### ISSUE TITLE
[Bug] Settling Probe: Internal error during connect: PrinterProbe.__init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by staticanime** [voidtrance/voron-klipper-extensions#10]
**Describe the bug**
Klipper reports error on Startup:
Internal error during connect: PrinterProbe.__init__() takes 2 positional arguments but 3 were given

Klippy.log shows below error
`Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klippy/extras/settling_probe.py", line 91, in load_config
    return SettlingProbe(config)
  File "/home/pi/klipper/klippy/extras/settling_probe.py", line 38, in __init__
    PrinterProbe.__init__(self, probe_config, mcu_probe)
TypeError: PrinterProbe.__init__() takes 2 positional arguments but 3 were given
webhooks client 281473169529664: New connection
webhooks client 281473169529664: Client info {'program': 'Moonraker', 'version': 'v0.8.0-379-g346a3d7'}`

**To Reproduce**
1. Running klipper v0.12.0-205
2. Running voron-klipper-extensions v0.0.1-39
3. Have [settling_probe] section in printer.cfg
4. Update klipper to v0.12.0-229

**Expected behavior**
Klipper initialises successfully

**Screenshots**

**Repository Versions**
Please, provide the head commit of the following repositories:
- Klipper: v0.12.0-229-g589bd64c
- voron-klipper-extensions: v0.0.1-39-g46c7c31a
- Moonraker: v0.8.0-379-g346a3d7c

**Additional context**
It looks like there is a rework ongoing in klipper of the probe code, and it seems the error is related to the settling sample code, so presumably needs reworked to match the klipper changes. Raising this bug for awareness, suspect it's best to wait until the rework of the probe code is complete.

**Comment by iitsalex** [comment]
Also ran into this bug, I did some super surface level editing of the script to change it to pass just two parameters to the __init__() but wasn't able to get it to work. Just reverted to a prior version of klipper for the time being.

**Comment by voidtrance** [comment]
This has already been fixed with the latest update (commit 4dc2641). Closing this issue.
