### ISSUE TITLE
[Bug] Settling_Probe causing an error when performing a PROBE_ACCURACY

### ISSUE THREAD

**Issue by CBoismenu** [voidtrance/voron-klipper-extensions#11]
**Describe the bug**
Performing a PROBE_ACCURACY with settling_probe enabled causes an Internal error on command "PROBE_ACCURACY", a firmware restart is needed to initialize the printer

**To Reproduce**
1. Home all Axes
2. Type PROBE_ACCURACY in the Console
3. Generates the following error: Internal error on command "PROBE_ACCURACY" 

**Expected behavior**
The command should not cause an error and stop the printer.
QUAD_GANTRY_LEVEL and BED_MESH work as expected (ignoring the settling sample and averaging the other values)

If the settling_probe is disabled PROBE_ACCURACY works as expected.

**Repository Verions**
Please, provide the head commit of the following repositories:
- Klipper: v0.12.0-230-g0d87bec1
- voron-klipper-extensions: v0.0.1-40-g4dc2641a
- Moonraker: v0.8.0-379-g346a3d7c

**Comment by CBoismenu** [comment]
Will do as soon as I get home.

**Comment by voidtrance** [comment]
> Will do as soon as I get home.

Don't worry. I was able to reproduce it locally.
I have a fix. I'll do some local testing and if all is well should be able to post the fix later today.

**Comment by CBoismenu** [comment]
OK Thanks for all your work.
