### ISSUE TITLE
[FEATURE]Multiple settling samples

### ISSUE THREAD

**Issue by Fuechsl** [voidtrance/voron-klipper-extensions#15]
**Is your feature request related to a problem? Please describe.**
As described [here](https://github.com/voidtrance/voron-klipper-extensions/discussions/6) my printer configuration (bed, gantry, whatever) sometimes needs more than 1 settling sample 

**Describe the solution you'd like**
it would be great to be able to pass a parameter for the number of settling samples to the script.

**Describe alternatives you've considered**
I've considered just modify the script myself so on my printer it does 2 settling samples instead of 1.

**Additional context**
Since I can't write python code, I've asked ChatGPT for the changes I would have to do. It said to add this line:

`self.settling_sample_count = config.getint('settling_sample_count', 1) if self.settling_sample else 0`

to SettlingProbeSessionHelper.__init__

and

`for i in range(self.settling_sample_count):
    gcmd.respond_info(f"Performing settling sample {i + 1} of {self.settling_sample_count}...")
    pos = self._probe(speed)
    toolhead.manual_move(probexy + [pos[2] + sample_retract_dist], lift_speed)`

to _run_settling_probe.

What do you think?

**Comment by voidtrance** [comment]
ChatGPT is almost correct. I mean, what it suggests will work but it's not as clean as it can be. I can try to add this to the extension in the next week.

**Comment by voidtrance** [comment]
Update: I have an implementation but I haven't had the time to test it yet.

**Comment by Fuechsl** [comment]
Great! Thanks for your effort - same here, not much time to tinker at the moment. So, take your time or tell me, if I can help testing (towards the end of the week and next week, things look less dense).

**Comment by voidtrance** [comment]
This is the change that I am planning on committing. Go ahead and try it. Let me know how it's working for you?
[settling_probe.patch](https://github.com/user-attachments/files/17779368/settling_probe.patch)

**Comment by Fuechsl** [comment]
Thanks for your work. Dummy question: How do I apply your patch file?

**Comment by voidtrance** [comment]
Download it and transfer it to your Pi. Put it in the `~/voron-klipper-extensions` folder. Then run `patch -p1 < settling_probe.patch`

**Comment by Fuechsl** [comment]
I've just tried it, works like a charm, thanks a lot! I've set it to 3 samples to discard, after three rounds of a voron 2.4 350mm not used for 2 weeks or so it was down to 0.003 deviation. Before, with only one sample discarded, it took me like 5-6 rounds to get the gantry even, sometimes it even failed completely (I think it's due to my bed giving in just a tiny bit being touched by the nozzle).

**Comment by voidtrance** [comment]
Change has been pushed. Closing.
