### ISSUE TITLE
[Bug] state_notify without `[menu]` config

### ISSUE THREAD

**Issue by rootiest** [voidtrance/voron-klipper-extensions#4]
**Describe the bug**
The state_notify extension errors out on boot if you do not have a `[menu]` configured (or a `[display]` that enables the default one)

**To Reproduce**
1. Add `[state_notify]` to your config
2. Don't have a klipper `[display]` with a menu
3. See error: Internal error during ready callback: Unknown config object 'menu'

**Expected behavior**
Modify the behavior to account for those scenarios or maybe just mention the requirement in the docs.

**Screenshots**
![error message](https://i.imgur.com/11HSCLT.png)

**Repository Versions**
Please, provide the head commit of the following repositories:
- Klipper v0.11.0-240-g6d48adf9
- voron-klipper-extensions v0.0.1-21-g30aa9ca
- Moonraker v0.8.0-87-g8eddec8

**Log**
[Klippy Log](https://gist.github.com/rootiest/1afd92c9ba190641b38ffc71473cc244)

**Additional context**
Essentially it just appears that `[state_notify]` requires a `[menu]` to be configured, but the documentation does not mention this requirement at all. Looking through the code quickly, I don't know how feasible it would be to bypass this requirement, so maybe just mentioning it in the docs would be simplest.

**Comment by voidtrance** [comment]
Hi @rootiest, thank you for reporting the issue.

I think I did find a way to avoid requiring the menu/display section to be present. I'll try testing it on my printer but if I am unsuccessful for some reason, would you mind testing a fix for me?

**Comment by rootiest** [comment]
@voidtrance Sure! I can test it out

**Comment by voidtrance** [comment]
Bug has been fixed. Closing issue.
