### ISSUE TITLE
[Bug] on_idle_gcode is required

### ISSUE THREAD

**Issue by rootiest** [voidtrance/voron-klipper-extensions#8]
**Describe the bug**
Since a recent update `on_idle_gcode` must be included even if that function is not used.
I use `state_notify` but currently only for the `on_ready_gcode` so I am not using the `idle_state` functionality at all.
Yet it is still being required.
I simply created an empty config entry for it, but perhaps it doesn't **_need_** to be mandatory?

**To Reproduce**
1. Include `[state_notify]` in your config
2. Don't use `on_idle_gcode`
3. Receive error

**Expected behavior**
'on_idle_gcode' shouldn't be mandatory if it's not being used. Or the documentation should mention it :)

**Screenshots**
![Screenshot_20231108_083150](https://github.com/voidtrance/voron-klipper-extensions/assets/38051220/48be2a2b-9ad3-4e01-b60b-7ccdac04d9e6)

**Repository Verions**
Please, provide the head commit of the following repositories:
- Klipper v0.11.0-308
- voron-klipper-extensions v0.0.1-30-g4fb8af14
- Moonraker v0.8.0-197-g975011d1

**Comment by voidtrance** [comment]
Issue fixed by commit 912125d.
